= Vaccination scheduling (Java, Quarkus, Maven)

== Postgresql 

A Postgresql database is needed to support this vaccination scheduling application.

. A local containerized postgresql can be instantiated as follows:
+
-----
$ podman run -d \
      --publish 5432:5432 \
      --name psql_vaccine \
      -e POSTGRESQL_USER=vaccine \
      -e POSTGRESQL_PASSWORD=vaccine \
      -e POSTGRESQL_DATABASE=vaccine \
      -e POSTGRESQL_MAX_PREPARED_TRANSACTIONS=10 \
      registry.redhat.io/rhel8/postgresql-12
-----

. Initialize the vaccine database of postgresql:
+
-----
$ psql -h 127.0.0.1 -U vaccine -d vaccine -a -f src/main/resources/db/V1_appointment_table_create.sql
-----

== Run the application with live coding

. Start the application:
+
[source, shell]
----
$ mvn quarkus:dev
----

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

Then try _live coding_:

. Make some changes in the source code.
. Refresh your browser (F5).

Notice that those changes are immediately in effect.

== RESTful API

The vaccination scheduling application exposes RESTful APIs.
The OpenAPI documentation pertaining to these RESTful APIs are available by navigating in a browser to: http://localhost:8080/q/swagger-ui/

== Deployment to OCP

. build image
+
-----
$ podman build -f docker/Dockerfile -t quay.io/redhat_naps_da/vaccination_scheduling:jbride-363f9f4-2 . 
-----

. push image
+
-----
$ podman push quay.io/redhat_naps_da/vaccination_scheduling:jbride-363f9f4-2
-----

. Create IS
+
-----
$ oc import-image vaccination_scheduling --all=true --from=quay.io/redhat_naps_da/vaccination_scheduling --confirm
-----

