:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= Vaccination Scheduling 
:numbered:

== Overview

The purpose of this guide is to provide technical documentation on the Red Hat vaccine scheduling demo.

Other related documentation and project management can be found as follows:

. link:https://docs.google.com/document/d/1q5WpnbfVyXq52lz2Wmd09m-ABWb0yoZqf7p73D5cjSA/edit[Design Doc]
. link:https://issues.redhat.com/browse/NAPSSS-12[Issues / Project Mgmt]
. link:https://trello.com/c/8qaUwRM2/66-vaccine-optaplanner-solution-architecture-and-demo[Trello Status]

== Demo Script

TO_DO

== Technologies

. Red Hat Build of Quarkus
. SmallRye
. PostgreSQL
. Optaplanner
. Maven
. Ansible
. OpenShift Container Platform
. 3scale API Management
. Swagger / OpenAPI
. Podman
. link:quay.io/redhat_naps_da/vaccination_scheduling[Quay]


== Local Dev Environment

=== Postgresql 

A Postgresql database is needed to support this vaccination scheduling application.

. A local containerized postgresql can be instantiated as follows:
+
-----
$ podman run -d \
      --publish 5432:5432 \
      --name psql_vaccine \
      -e POSTGRESQL_USER=vaccine \
      -e POSTGRESQL_PASSWORD=vaccine \
      -e POSTGRESQL_DATABASE=vaccine \
      -e POSTGRESQL_MAX_PREPARED_TRANSACTIONS=10 \
      registry.redhat.io/rhel8/postgresql-12
-----

. Initialize the vaccine database of postgresql:
+
-----
$ psql -h 127.0.0.1 -U vaccine -d vaccine -a -f src/main/resources/db/V1_appointment_table_create.sql
-----

=== Run the application with live coding

. Start the application:
+
[source, shell]
----
$ mvn quarkus:dev
----

. Visit http://localhost:8080 in your browser.

. Click on the *Solve* button.

Then try _live coding_:

. Make some changes in the source code.
. Refresh your browser (F5).

Notice that those changes are immediately in effect.

=== RESTful API

The vaccination scheduling application exposes RESTful APIs.

The OpenAPI documentation pertaining to these RESTful APIs are available by navigating in a browser to: http://localhost:8080/q/swagger-ui/

== Packaging and Deployment to OCP

=== Vaccination Scheduling container image

. build image
+
-----
$ mvn clean package -DskipTests
$ podman build -f docker/Dockerfile -t quay.io/redhat_naps_da/vaccination_scheduling:jbride-363f9f4-3 . 
-----

. push image
+
-----
$ podman push quay.io/redhat_naps_da/vaccination_scheduling:jbride-363f9f4-3
-----

. Create IS
+
-----
$ oc import-image v-scheduler --all=true --from=quay.io/redhat_naps_da/vaccination_scheduling --confirm
-----

=== Deployment to OCP

Deployment to OCP is done in an automated, repeatable manner using ansible.
The ansible is included in this project and deploys the following:

* 3scale tenant
* 3scale apicast gateways 
* vaccination scheduling quarkus app and database

. This section assumes that a 3scale tenant has already been created

. Set an environment variable that captures the tenant admin access token:
+
-----
# Acquired as per the following in 3scale tenant:  `Gear Icon -> Personal Settings -> Tokens -> Access Tokens -> Add Access Token`
$ tenant_admin_accesstoken=c06015d7fba524064feaf5ae6b24e1a8
-----

. Set an environment variable that captures the hostname of the 3scale admin portal:
+
-----
$ tenant_admin_hostname=vplanner-admin.apps.rhtnckpmg.rhsledocp.com
-----

-----
$ ansible-playbook playbooks/threescale.yml \
      -e threescale_portal_accesstoken=$tenant_admin_accesstoken \
      -e threescale_portal_hostname=$tenant_admin_hostname
-----

=== Test

. Set 3scale application userkey as an environment variable:
+
-----
$ API_APP_KEY=2603edadc49ff2fddc4de8b2490cefd6
-----

. GET openapi in yaml format:
+
-----
$ wget https://prod-apicast-v-scheduling-user1.apps.rhtnckpmg.rhsledocp.com/q/openapi?user_key=$API_APP_KEY \
       -O openapi.yml
-----

. Start solver
+
-----
$ curl -v -X POST \
       -H "Content-Type: application/json" \
       https://prod-apicast-v-scheduling-user1.apps.rhtnckpmg.rhsledocp.com/vaccinationSchedule/solve?user_key=$API_APP_KEY
-----

. Stop solver
+
-----
$ curl -v -X POST \
       -H "Content-Type: application/json" \
       https://prod-apicast-v-scheduling-user1.apps.rhtnckpmg.rhsledocp.com/vaccinationSchedule/stopSolving?user_key=$API_APP_KEY
-----

. GET solution
+
-----
$ curl -v -X GET \
       -H "Content-Type: application/json" \
       https://prod-apicast-v-scheduling-user1.apps.rhtnckpmg.rhsledocp.com/vaccinationSchedule?user_key=$API_APP_KEY
-----

== Bootstrap a Vaccine Scheduling Runtime w/ Demo Data

Prior to solving a vaccination scheduling problem, domain specific seed data must be parsed and made available to the planning engine.

Example seed data is included in this project and found at the following:  `src/main/resources/mocks/original_vaccination_schedule_mock.json`

The seed data is expected in a json representation.

Different seed data can be made available to the planning engine via the following java system property:  `com.redhat.vaccination.scheduling.seed.file.path`

When deploying the vaccination scheduling demo to openshift via ansible, the link:https://github.com/redhat-naps-da/vaccination-scheduling/blob/master/ansible/roles/vaccination_scheduler/defaults/main.yml#L33[v_scheduling_seed_data_file] property defines the json data file to load.


