---

- name: delete deployment config
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete imagestream in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: "delete configmap {{ application_configmap }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: "delete configmap {{ v_scheduling_seed_configmap }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ v_scheduling_seed_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap
