---

home_dir: "{{ playbook_dir }}/.."

# resources dir
resources_base_dir: "{{ home_dir }}/resources"

# oc executable
openshift_cli: oc

project_admin: user1

project_name: "v-scheduling-{{ project_admin }}"

deploy_from: image


