---

home_dir: "{{ playbook_dir }}/.."

# resources dir
resources_base_dir: "{{ home_dir }}/resources"

# oc executable
openshift_cli: oc

project_admin: user1

project_name: "v-planner-{{ project_admin }}"

deploy_from: image

fhir_server_application_name: fhir-server


